//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinal {
	
	
	public partial class Create {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DataGrid DataGrid1;
		
		protected System.Web.UI.WebControls.Label errorlabel;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Label namelabel;
		
		protected System.Web.UI.WebControls.TextBox namebox;
		
		protected System.Web.UI.WebControls.Label agelabel;
		
		protected System.Web.UI.WebControls.TextBox agebox;
		
		protected System.Web.UI.WebControls.Label passwordlabel;
		
		protected System.Web.UI.WebControls.TextBox passwordbox;
		
		protected System.Web.UI.WebControls.Label province_practicelabel;
		
		protected System.Web.UI.WebControls.TextBox province_practicebox;
		
		protected System.Web.UI.WebControls.Button Submit_Button;
		
		protected System.Web.UI.WebControls.Label last_namelabel;
		
		protected System.Web.UI.WebControls.TextBox last_namebox;
		
		protected System.Web.UI.WebControls.Label emaillabel;
		
		protected System.Web.UI.WebControls.TextBox emailbox;
		
		protected System.Web.UI.WebControls.Label collegiate_numberlabel;
		
		protected System.Web.UI.WebControls.TextBox collegiate_numberbox;
		
		protected System.Web.UI.WebControls.Label specialtylabel;
		
		protected System.Web.UI.WebControls.TextBox specialtybox;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink1;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink2;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink3;
	}
}
