//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinal {
	
	
	public partial class Delete {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DataGrid DataGrid1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.ListBox ListBox1;
		
		protected System.Web.UI.WebControls.Button Submit_Button;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink1;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink2;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink3;
	}
}
